### ISSUE TITLE
Else and ElseIf statements should always be in new line

### ISSUE THREAD

**Issue by pravynandas** [noraj/vbsmin#32]

**Comment by noraj** [comment]
Hi @pravynandas 

Could you provide an example?

**Comment by pravynandas** [comment]
Issue title updated. I will share the test results in sometime.

**Comment by noraj** [comment]
Closing as there is no details

**Comment by ildar-shaimordanov** [comment]
A year ago I've been interested in writing vbs-minifier using vbs only. That time I found your project and tried to adapt it as I wanted. Now I decided to rewrite it. And I ran into the issue of the if/then/else statement. I've tried to collect everything in this repository https://github.com/ildar-shaimordanov/vbsmin-vbs.

**Comment by noraj** [comment]
Weird because I successfully executed some onelined if/then/else statement in the past.

**Comment by ildar-shaimordanov** [comment]
I used one of the previous ruby-based vbsmin implementations (that's not important in this case). You can try with the `*-1-original.vbs` examples from https://github.com/ildar-shaimordanov/vbsmin-vbs/tree/main/data/failure to compare and check. Both your and my vbsmin produce almost identical minified code (except internal whitespaces). An both fail on them.
