### ISSUE TITLE
False comment recognition

### ISSUE THREAD

**Issue by ildar-shaimordanov** [noraj/vbsmin#50]
Example:
```vbs
Dim Remark
Remark = 0
```

Expected:
```vbs
Dim Remark:Remark = 0
```

In fact:
```vbs
Dim Remark:
```

It's caused because of it:
https://github.com/noraj/vbsmin/blob/aeeadcfce793dae9d1688ac7997952389db11c90/lib/vbsmin.rb#L54

The following patch (replacement) can fix this issue:
```rb
        line = '' if /^(?:'|rem\b)/i =~ line
```

**Comment by noraj** [comment]
Yeah `line[0..2].upcase == 'REM'` should have been `line[0..3].upcase == 'REM '` but you regexp is better, I'll add this patch. Thanks

**Comment by ildar-shaimordanov** [comment]
My first approach was almost the same - I tried to capture `REM` with the following a whitespace or TAB. Later I found that any non-alphanumeric text following `REM` is a comment. So the only and easy way is to capture `REM` and the following zero-length whitespace `\b`.

I'd like to keep both our projects consistent each other in terms of results.
